### ISSUE TITLE
Move native to optionalDependency?

### ISSUE THREAD

**Issue by junderw** [cryptocoinjs/keccak#11]
tiny-secp256k1 did so, and it at least allows failed installs to fallback on the JS as intended.

@fanatid thoughts?

Also kind of want to do something similar with node-secp256k1

**Comment by fanatid** [comment]
`install` command not work in some cases? https://github.com/cryptocoinjs/keccak/blob/bce5b58e8e5e3d17bcb681fa2814dbe8dd893841/package.json#L34

JS and native highly tied, they implement only basic API which extended by shared functions
https://github.com/cryptocoinjs/keccak/blob/master/lib/api/index.js

**Comment by junderw** [comment]
apparently #3 tells me people are getting errors

**Comment by junderw** [comment]
Nevermind... I tested it myself in an alpine container... seems like an install script is better idea.

**Comment by junderw** [comment]
https://github.com/bitcoinjs/tiny-secp256k1/pull/41
