### ISSUE TITLE
 error C2660: “v8::Value::IntegerValue”

### ISSUE THREAD

**Issue by johnzhu12** [cryptocoinjs/keccak#20]
F:\11\web-front\node_modules\_keccak@1.4.0@keccak\src\addon.cc(37,1): error C2660: “v8::Value::IntegerValue”: 函数不接受 0 个
参数 [F:\11\web-front\node_modules\_keccak@1.4.0@keccak\build\keccak.vcxproj]
C:\Users\STRIX\AppData\Local\node-gyp\Cache\12.11.1\include\node\v8.h(2609,40): message : 参见“v8::Value::IntegerValue”的声
明 (编译源文件 ..\src\addon.cc) [F:\11\web-front\node_modules\_keccak@1.4.0@keccak\build\keccak.vcxproj]
F:\11\web-front\node_modules\_keccak@1.4.0@keccak\src\addon.cc(38,1): error C2660: “v8::Value::IntegerValue”: 函数不接受 0 个
参数 [F:\11\web-front\node_modules\_keccak@1.4.0@keccak\build\keccak.vcxproj]
C:\Users\STRIX\AppData\Local\node-gyp\Cache\12.11.1\include\node\v8.h(2609,40): message : 参见“v8::Value::IntegerValue”的声
明 (编译源文件 ..\src\addon.cc) [F:\11\web-front\node_modules\_keccak@1.4.0@keccak\build\keccak.vcxproj]
F:\11\web-front\node_modules\_keccak@1.4.0@keccak\src\addon.cc(56,1): error C2660: “v8::Value::IntegerValue”: 函数不接受 0 个
参数 [F:\11\web-front\node_modules\_keccak@1.4.0@keccak\build\keccak.vcxproj]
C:\Users\STRIX\AppData\Local\node-gyp\Cache\12.11.1\include\node\v8.h(2609,40): message : 参见“v8::Value::IntegerValue”的声
明 (编译源文件 ..\src\addon.cc) [F:\11\web-front\node_modules\_keccak@1.4.0@keccak\build\keccak.vcxproj]
F:\11\web-front\node_modules\_keccak@1.4.0@keccak\src\addon.cc(64,1): error C2660: “v8::Value::IntegerValue”: 函数不接受 0 个
参数 [F:\11\web-front\node_modules\_keccak@1.4.0@keccak\build\keccak.vcxproj]
C:\Users\STRIX\AppData\Local\node-gyp\Cache\12.11.1\include\node\v8.h(2609,40): message : 参见“v8::Value::IntegerValue”的声
明 (编译源文件 ..\src\addon.cc) [F:\11\web-front\node_modules\_keccak@1.4.0@keccak\build\keccak.vcxproj]
F:\11\web-front\node_modules\_keccak@1.4.0@keccak\src\addon.cc(75,1): error C2661: “v8::Value::ToObject”: 没有重载函数接受 0 个参
数 [F:\11\web-front\node_modules\_keccak@1.4.0@keccak\build\keccak.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `d:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\STRIX\AppData\Roaming\nvm\v12.11.1\node_modules\npm\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\STRIX\\AppData\\Roaming\\nvm\\v12.11.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd F:\11\web-front\node_modules\_keccak@1.4.0@keccak
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\STRIX\.npminstall_tarball\_logs\2020-11-18T07_46_08_126Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

**Comment by Tuditi** [comment]
I'm encountering a similar issue [here](https://github.com/iotaledger/firefly/actions/runs/5284776862). Any ideas on how to solve this?
