### ISSUE TITLE
How to hash an array of objects

### ISSUE THREAD

**Issue by ansermino** [cryptocoinjs/keccak#5]
What is the best way to hash an array of objects (in my case BigNumbers)? It seems that array support is limited to primitive types.

**Comment by fanatid** [comment]
Convert objects to strings, concatenate with some symbol (otherwise ['aa', 'b'] can be equal to ['a', 'ab']) and apply hash to string.

**Comment by ansermino** [comment]
Big thanks for the quick reply!
